import type {A2UIVersion} from './types.js';
function modernText(id: string, text: string, variant?: string) { return { id, component: 'Text', text, ...(variant ? {variant} : {}) }; }
function modernButton(id: string, child: string, actionName: string, variant?: string) { return { id, component: 'Button', child, action: { event: { name: actionName, context: { source: 'generate-a2ui' } } }, ...(variant ? {variant} : {}) }; }
function modernAlert(version: 'v0.9' | 'v0.10', surfaceId: string) { return [{ version, createSurface: { surfaceId, catalogId: `https://a2ui.org/specification/${version.replace('.', '_')}/basic_catalog.json`, theme: { primaryColor: '#0f766e', font: 'Pretendard, system-ui, sans-serif' }, sendDataModel: true } }, { version, updateComponents: { surfaceId, components: [{ id: 'root', component: 'Card', child: 'layout' }, { id: 'layout', component: 'Column', children: ['title', 'detail', 'actions'] }, modernText('title', '경고', 'h3'), modernText('detail', '계속 진행할지 선택해 주세요.', 'body'), { id: 'actions', component: 'Row', children: ['cancel', 'confirm'], justify: 'end' }, modernButton('cancel', 'cancel_label', 'cancel', 'default'), modernText('cancel_label', '취소', 'body'), modernButton('confirm', 'confirm_label', 'confirm', 'primary'), modernText('confirm_label', '확인', 'body')] } }]; }
function modernLogin(version: 'v0.9' | 'v0.10', surfaceId: string) { return [{ version, createSurface: { surfaceId, catalogId: `https://a2ui.org/specification/${version.replace('.', '_')}/basic_catalog.json`, theme: { primaryColor: '#1d4ed8', font: 'Pretendard, system-ui, sans-serif' }, sendDataModel: true } }, { version, updateDataModel: { surfaceId, path: '/', value: { email: '', password: '', rememberMe: true } } }, { version, updateComponents: { surfaceId, components: [{ id: 'root', component: 'Card', child: 'form' }, { id: 'form', component: 'Column', children: ['heading', 'subheading', 'email', 'password', 'remember', 'submit'] }, modernText('heading', '로그인', 'h2'), modernText('subheading', '계정으로 계속 진행하세요.', 'caption'), { id: 'email', component: 'TextField', label: '이메일', value: { path: '/email' }, variant: 'shortText' }, { id: 'password', component: 'TextField', label: '비밀번호', value: { path: '/password' }, variant: 'obscured' }, { id: 'remember', component: 'CheckBox', label: '로그인 상태 유지', value: { path: '/rememberMe' } }, modernButton('submit', 'submit_label', 'login-submit', 'primary'), modernText('submit_label', '로그인', 'body')] } }]; }
function legacyAlert(surfaceId: string) { return [{ beginRendering: { surfaceId, root: 'root', styles: { primaryColor: '#0f766e', font: 'Pretendard, system-ui, sans-serif' } } }, { surfaceUpdate: { surfaceId, components: [{ id: 'root', component: { Card: { child: 'layout' } } }, { id: 'layout', component: { Column: { children: { explicitList: ['title', 'detail', 'actions'] } } } }, { id: 'title', component: { Text: { text: { literalString: '경고' }, usageHint: 'h3' } } }, { id: 'detail', component: { Text: { text: { literalString: '계속 진행할지 선택해 주세요.' }, usageHint: 'body' } } }, { id: 'actions', component: { Row: { children: { explicitList: ['cancel', 'confirm'] }, distribution: 'end' } } }, { id: 'cancel_label', component: { Text: { text: { literalString: '취소' } } } }, { id: 'confirm_label', component: { Text: { text: { literalString: '확인' } } } }, { id: 'cancel', component: { Button: { child: 'cancel_label', action: { name: 'cancel' } } } }, { id: 'confirm', component: { Button: { child: 'confirm_label', primary: true, action: { name: 'confirm' } } } }] } }]; }
function legacyLogin(surfaceId: string) { return [{ beginRendering: { surfaceId, root: 'root', styles: { primaryColor: '#1d4ed8', font: 'Pretendard, system-ui, sans-serif' } } }, { dataModelUpdate: { surfaceId, contents: [{ key: 'email', valueString: '' }, { key: 'password', valueString: '' }, { key: 'rememberMe', valueBoolean: true }] } }, { surfaceUpdate: { surfaceId, components: [{ id: 'root', component: { Card: { child: 'form' } } }, { id: 'form', component: { Column: { children: { explicitList: ['heading', 'subheading', 'email', 'password', 'remember', 'submit'] } } } }, { id: 'heading', component: { Text: { text: { literalString: '로그인' }, usageHint: 'h2' } } }, { id: 'subheading', component: { Text: { text: { literalString: '계정으로 계속 진행하세요.' }, usageHint: 'caption' } } }, { id: 'email', component: { TextField: { label: { literalString: '이메일' }, text: { path: '/email' }, textFieldType: 'shortText' } } }, { id: 'password', component: { TextField: { label: { literalString: '비밀번호' }, text: { path: '/password' }, textFieldType: 'obscured' } } }, { id: 'remember', component: { CheckBox: { label: { literalString: '로그인 상태 유지' }, value: { path: '/rememberMe' } } } }, { id: 'submit_label', component: { Text: { text: { literalString: '로그인' } } } }, { id: 'submit', component: { Button: { child: 'submit_label', primary: true, action: { name: 'login-submit' } } } }] } }]; }
export function generateFallbackMessages(version: A2UIVersion, prompt: string, surfaceId = 'main'): unknown[] {
  const isLogin = /(login|signin|로그인)/i.test(prompt);
  if (version === 'v0.8') return isLogin ? legacyLogin(surfaceId) : legacyAlert(surfaceId);
  return isLogin ? modernLogin(version, surfaceId) : modernAlert(version, surfaceId);
}
